### ISSUE TITLE
Thermal engines not scaling properly

### ISSUE THREAD

**Issue by Regularitee** [confusingbits/KSPInterstellar#33]
I know WaveFunction previously closed the thread on electric engines under the belief the thermal engines were also working as intended, but as of 12.1 they are not.

When placed on a scaled-down reactor of corresponding size, they appear fine in the VAB, and even have the proper mass calculations in mechjeb. But when launched they turn into the default sized 2.5m engines. Also when the saved ship is re-opened in the VAB, mechjeb will give a different number for mass compared to when it was saved -- likely as if it were the 2.5m version, even if the model is still displaying a smaller size.

**Comment by confusingbits** [comment]
I suspect you have an interaction with another addon going on or you didn't remove the duplicate configs from a full install of tweakscale. See the installation video for instructions.

**Comment by Regularitee** [comment]
Someone else mentioned the issue yesterday, while mentioning his attempt to fix electric engines:

http://forum.kerbalspaceprogram.com/threads/91867-0-24-2-Interstellar-Lite-Tweakscale-Integration-v0-12-2-Aug-29?p=1381352&viewfull=1#post1381352

He seems to know more about the cause of the issue than I, so hopefully can shed light on the cause of the issue. It could be that he also has an incorrect installation... but if not, then maybe he could shed some light on the nature of this bug.

**Comment by confusingbits** [comment]
Yes, I responded to the electric engine issue. A fix has already be published in .12.2. It was just a missing tweakscale config for electric engines :)

Thermal nozzles are working as intended. I have quite literally done hundreds of tests during reactor balancing with thermal engines. They don't need a special config, the nozzle part module already handles it natively.

I sent you to watch the video because it shows you how to cleanly install and how to report issues if you find them. I'd love to help, but I have nothing to go on. If it is an issue, it is not happening with a clean install, so we need to find out what mod is causing the issue.
